// <auto-generated />
using System;
using FSM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FSM.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260524165021_initiaalProjectII")]
    partial class initiaalProjectII
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FSM.Models.Freelancer", b =>
                {
                    b.Property<int>("FreelancerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FreelancerID"));

                    b.Property<string>("FreelancerBio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FreelancerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FreelancerFName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FreelancerLName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FreelancerID");

                    b.ToTable("Freelancers");

                    b.HasData(
                        new
                        {
                            FreelancerID = 1,
                            FreelancerBio = "Front-end developer specializing in React and UI design.",
                            FreelancerEmail = "alice.johnson@example.com",
                            FreelancerFName = "Alice",
                            FreelancerLName = "Johnson"
                        },
                        new
                        {
                            FreelancerID = 2,
                            FreelancerBio = "Full-stack engineer with experience in ASP.NET Core and SQL Server.",
                            FreelancerEmail = "brian.smith@example.com",
                            FreelancerFName = "Brian",
                            FreelancerLName = "Smith"
                        },
                        new
                        {
                            FreelancerID = 3,
                            FreelancerBio = "Data analyst passionate about turning raw data into insights.",
                            FreelancerEmail = "carla.nguyen@example.com",
                            FreelancerFName = "Carla",
                            FreelancerLName = "Nguyen"
                        },
                        new
                        {
                            FreelancerID = 4,
                            FreelancerBio = "Mobile app developer focusing on Android and Kotlin.",
                            FreelancerEmail = "david.brown@example.com",
                            FreelancerFName = "David",
                            FreelancerLName = "Brown"
                        },
                        new
                        {
                            FreelancerID = 5,
                            FreelancerBio = "UX researcher with a background in psychology and design.",
                            FreelancerEmail = "ella.martinez@example.com",
                            FreelancerFName = "Ella",
                            FreelancerLName = "Martinez"
                        },
                        new
                        {
                            FreelancerID = 6,
                            FreelancerBio = "Cloud solutions architect experienced in Azure and AWS.",
                            FreelancerEmail = "felix.garcia@example.com",
                            FreelancerFName = "Felix",
                            FreelancerLName = "Garcia"
                        },
                        new
                        {
                            FreelancerID = 7,
                            FreelancerBio = "Content writer specializing in technical documentation.",
                            FreelancerEmail = "grace.lee@example.com",
                            FreelancerFName = "Grace",
                            FreelancerLName = "Lee"
                        },
                        new
                        {
                            FreelancerID = 8,
                            FreelancerBio = "Cybersecurity consultant with penetration testing expertise.",
                            FreelancerEmail = "henry.wilson@example.com",
                            FreelancerFName = "Henry",
                            FreelancerLName = "Wilson"
                        },
                        new
                        {
                            FreelancerID = 9,
                            FreelancerBio = "Graphic designer skilled in Adobe Creative Suite.",
                            FreelancerEmail = "isabella.taylor@example.com",
                            FreelancerFName = "Isabella",
                            FreelancerLName = "Taylor"
                        },
                        new
                        {
                            FreelancerID = 10,
                            FreelancerBio = "Backend developer with strong knowledge of C# and APIs.",
                            FreelancerEmail = "jack.harris@example.com",
                            FreelancerFName = "Jack",
                            FreelancerLName = "Harris"
                        },
                        new
                        {
                            FreelancerID = 11,
                            FreelancerBio = "SEO specialist helping businesses grow their online presence.",
                            FreelancerEmail = "kylie.roberts@example.com",
                            FreelancerFName = "Kylie",
                            FreelancerLName = "Roberts"
                        },
                        new
                        {
                            FreelancerID = 12,
                            FreelancerBio = "Game developer with Unity and C# experience.",
                            FreelancerEmail = "liam.clark@example.com",
                            FreelancerFName = "Liam",
                            FreelancerLName = "Clark"
                        },
                        new
                        {
                            FreelancerID = 13,
                            FreelancerBio = "Project manager with Agile and Scrum certifications.",
                            FreelancerEmail = "maya.lopez@example.com",
                            FreelancerFName = "Maya",
                            FreelancerLName = "Lopez"
                        },
                        new
                        {
                            FreelancerID = 14,
                            FreelancerBio = "AI researcher working on natural language processing.",
                            FreelancerEmail = "noah.hall@example.com",
                            FreelancerFName = "Noah",
                            FreelancerLName = "Hall"
                        },
                        new
                        {
                            FreelancerID = 15,
                            FreelancerBio = "Marketing strategist with expertise in digital campaigns.",
                            FreelancerEmail = "olivia.allen@example.com",
                            FreelancerFName = "Olivia",
                            FreelancerLName = "Allen"
                        },
                        new
                        {
                            FreelancerID = 16,
                            FreelancerBio = "DevOps engineer automating CI/CD pipelines.",
                            FreelancerEmail = "paul.young@example.com",
                            FreelancerFName = "Paul",
                            FreelancerLName = "Young"
                        },
                        new
                        {
                            FreelancerID = 17,
                            FreelancerBio = "Copywriter crafting compelling brand stories.",
                            FreelancerEmail = "quinn.scott@example.com",
                            FreelancerFName = "Quinn",
                            FreelancerLName = "Scott"
                        },
                        new
                        {
                            FreelancerID = 18,
                            FreelancerBio = "Data scientist with Python and machine learning skills.",
                            FreelancerEmail = "rosa.king@example.com",
                            FreelancerFName = "Rosa",
                            FreelancerLName = "King"
                        },
                        new
                        {
                            FreelancerID = 19,
                            FreelancerBio = "IT support specialist with strong troubleshooting skills.",
                            FreelancerEmail = "sam.wright@example.com",
                            FreelancerFName = "Sam",
                            FreelancerLName = "Wright"
                        },
                        new
                        {
                            FreelancerID = 20,
                            FreelancerBio = "Social media manager growing communities online.",
                            FreelancerEmail = "tina.evans@example.com",
                            FreelancerFName = "Tina",
                            FreelancerLName = "Evans"
                        },
                        new
                        {
                            FreelancerID = 21,
                            FreelancerBio = "QA tester ensuring software quality and reliability.",
                            FreelancerEmail = "uma.hill@example.com",
                            FreelancerFName = "Uma",
                            FreelancerLName = "Hill"
                        },
                        new
                        {
                            FreelancerID = 22,
                            FreelancerBio = "Blockchain developer building decentralized applications.",
                            FreelancerEmail = "victor.green@example.com",
                            FreelancerFName = "Victor",
                            FreelancerLName = "Green"
                        },
                        new
                        {
                            FreelancerID = 23,
                            FreelancerBio = "Illustrator creating digital art and storyboards.",
                            FreelancerEmail = "wendy.adams@example.com",
                            FreelancerFName = "Wendy",
                            FreelancerLName = "Adams"
                        },
                        new
                        {
                            FreelancerID = 24,
                            FreelancerBio = "Systems analyst optimizing enterprise workflows.",
                            FreelancerEmail = "xavier.nelson@example.com",
                            FreelancerFName = "Xavier",
                            FreelancerLName = "Nelson"
                        },
                        new
                        {
                            FreelancerID = 25,
                            FreelancerBio = "Web developer specializing in responsive design.",
                            FreelancerEmail = "yara.bennett@example.com",
                            FreelancerFName = "Yara",
                            FreelancerLName = "Bennett"
                        });
                });

            modelBuilder.Entity("FSM.Models.Project", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectID"));

                    b.Property<decimal>("ProjectBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProjectDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProjectPostedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ProjectStatus")
                        .HasColumnType("bit");

                    b.Property<string>("ProjectTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectID");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ProjectID = 1,
                            ProjectBudget = 15000m,
                            ProjectDescription = "Develop a responsive online store with payment integration.",
                            ProjectPostedDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectStatus = true,
                            ProjectTitle = "E-Commerce Website"
                        },
                        new
                        {
                            ProjectID = 2,
                            ProjectBudget = 30000m,
                            ProjectDescription = "Create a secure mobile app for banking transactions.",
                            ProjectPostedDate = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectStatus = false,
                            ProjectTitle = "Mobile Banking App"
                        },
                        new
                        {
                            ProjectID = 3,
                            ProjectBudget = 12000m,
                            ProjectDescription = "Build a dashboard for visualizing business KPIs.",
                            ProjectPostedDate = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectStatus = true,
                            ProjectTitle = "Data Analytics Dashboard"
                        },
                        new
                        {
                            ProjectID = 4,
                            ProjectBudget = 8000m,
                            ProjectDescription = "Design and run a digital marketing campaign.",
                            ProjectPostedDate = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectStatus = true,
                            ProjectTitle = "Social Media Campaign"
                        },
                        new
                        {
                            ProjectID = 5,
                            ProjectBudget = 20000m,
                            ProjectDescription = "Develop a system to track stock levels and sales.",
                            ProjectPostedDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectStatus = false,
                            ProjectTitle = "Inventory Management System"
                        },
                        new
                        {
                            ProjectID = 6,
                            ProjectBudget = 18000m,
                            ProjectDescription = "Implement a customer support chatbot using NLP.",
                            ProjectPostedDate = new DateTime(2026, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectStatus = true,
                            ProjectTitle = "AI Chatbot"
                        },
                        new
                        {
                            ProjectID = 7,
                            ProjectBudget = 25000m,
                            ProjectDescription = "Create a platform for hosting online courses.",
                            ProjectPostedDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectStatus = false,
                            ProjectTitle = "Online Learning Platform"
                        },
                        new
                        {
                            ProjectID = 8,
                            ProjectBudget = 10000m,
                            ProjectDescription = "Develop a mobile app for food ordering and delivery.",
                            ProjectPostedDate = new DateTime(2026, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectStatus = true,
                            ProjectTitle = "Restaurant Ordering App"
                        },
                        new
                        {
                            ProjectID = 9,
                            ProjectBudget = 35000m,
                            ProjectDescription = "Build a secure cryptocurrency wallet application.",
                            ProjectPostedDate = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectStatus = false,
                            ProjectTitle = "Blockchain Wallet"
                        },
                        new
                        {
                            ProjectID = 10,
                            ProjectBudget = 12000m,
                            ProjectDescription = "Develop a wearable app for tracking workouts.",
                            ProjectPostedDate = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectStatus = true,
                            ProjectTitle = "Fitness Tracker"
                        },
                        new
                        {
                            ProjectID = 11,
                            ProjectBudget = 40000m,
                            ProjectDescription = "Create IoT solutions for home automation.",
                            ProjectPostedDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectStatus = false,
                            ProjectTitle = "Smart Home Automation"
                        },
                        new
                        {
                            ProjectID = 12,
                            ProjectBudget = 22000m,
                            ProjectDescription = "Develop a web app for booking flights and hotels.",
                            ProjectPostedDate = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectStatus = true,
                            ProjectTitle = "Travel Booking System"
                        },
                        new
                        {
                            ProjectID = 13,
                            ProjectBudget = 28000m,
                            ProjectDescription = "Build a patient management and appointment system.",
                            ProjectPostedDate = new DateTime(2026, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectStatus = false,
                            ProjectTitle = "Healthcare Portal"
                        },
                        new
                        {
                            ProjectID = 14,
                            ProjectBudget = 32000m,
                            ProjectDescription = "Develop a platform for streaming and sharing music.",
                            ProjectPostedDate = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectStatus = true,
                            ProjectTitle = "Music Streaming Service"
                        },
                        new
                        {
                            ProjectID = 15,
                            ProjectBudget = 15000m,
                            ProjectDescription = "Create a system for posting and applying to jobs.",
                            ProjectPostedDate = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectStatus = false,
                            ProjectTitle = "Job Recruitment Platform"
                        },
                        new
                        {
                            ProjectID = 16,
                            ProjectBudget = 17000m,
                            ProjectDescription = "Develop a platform for online bidding and auctions.",
                            ProjectPostedDate = new DateTime(2026, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectStatus = true,
                            ProjectTitle = "Online Auction Site"
                        },
                        new
                        {
                            ProjectID = 17,
                            ProjectBudget = 20000m,
                            ProjectDescription = "Create a mobile wallet for online payments.",
                            ProjectPostedDate = new DateTime(2026, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectStatus = false,
                            ProjectTitle = "Digital Wallet"
                        },
                        new
                        {
                            ProjectID = 18,
                            ProjectBudget = 14000m,
                            ProjectDescription = "Develop a system for managing events and tickets.",
                            ProjectPostedDate = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectStatus = true,
                            ProjectTitle = "Event Management System"
                        },
                        new
                        {
                            ProjectID = 19,
                            ProjectBudget = 16000m,
                            ProjectDescription = "Build a web app for grocery shopping and delivery.",
                            ProjectPostedDate = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectStatus = false,
                            ProjectTitle = "Online Grocery Store"
                        },
                        new
                        {
                            ProjectID = 20,
                            ProjectBudget = 9000m,
                            ProjectDescription = "Develop a mobile app for editing and sharing photos.",
                            ProjectPostedDate = new DateTime(2026, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectStatus = true,
                            ProjectTitle = "Photo Editing App"
                        },
                        new
                        {
                            ProjectID = 21,
                            ProjectBudget = 13000m,
                            ProjectDescription = "Create an app for learning new languages interactively.",
                            ProjectPostedDate = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectStatus = false,
                            ProjectTitle = "Language Learning App"
                        },
                        new
                        {
                            ProjectID = 22,
                            ProjectBudget = 21000m,
                            ProjectDescription = "Develop a platform for funding creative projects.",
                            ProjectPostedDate = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectStatus = true,
                            ProjectTitle = "Crowdfunding Platform"
                        },
                        new
                        {
                            ProjectID = 23,
                            ProjectBudget = 7000m,
                            ProjectDescription = "Build a tool for creating and analyzing surveys.",
                            ProjectPostedDate = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectStatus = false,
                            ProjectTitle = "Online Survey Tool"
                        },
                        new
                        {
                            ProjectID = 24,
                            ProjectBudget = 11000m,
                            ProjectDescription = "Develop a platform for hosting and streaming podcasts.",
                            ProjectPostedDate = new DateTime(2026, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectStatus = true,
                            ProjectTitle = "Podcast Hosting Service"
                        },
                        new
                        {
                            ProjectID = 25,
                            ProjectBudget = 26000m,
                            ProjectDescription = "Create a marketplace for hiring freelancers.",
                            ProjectPostedDate = new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectStatus = false,
                            ProjectTitle = "Freelancer Marketplace"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
